name: Syntaxes
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v19
        uses: actions/setup-node@v2
        with:
          node-version: 19
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lintCheck
